# Use postgres/example user/password credentials

networks:
  internal-network:
    internal: true

services:

  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    networks:
      - internal-network
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
      POSTGRES_DB: db
    ports:
      - 5173:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
